In [ ]:
!pip install tensorflow

In [ ]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
string = tf.Variable("this is a string", tf.string)
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>


In [ ]:
number = tf.Variable(838, tf.int16)
floating = tf.Variable(3.567, tf.float64)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


In [ ]:
# Rank/Degree of Tensors
rank1_tensor = tf.Variable([["sto at the nail salon", "lorde"], ["hi", "bi"]], tf.string)
print(rank1_tensor)


<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'sto at the nail salon', b'lorde'],
       [b'hi', b'bi']], dtype=object)>


In [ ]:
# **To determine the rank** of a tensor we can call the following method.
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
# The rank of a tensor is direclty related to the deepest level of nested lists. 
# You can see in the first example ["Test"] is a rank 1 tensor as the deepest level of nesting is 1.
# Where in the second example [["test", "ok"], ["test", "yes"]] 
# is a rank 2 tensor as the deepest level of nesting is 2.

In [ ]:
# . The shape of a tensor is simply the number of elements that exist in each dimension. 
# TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.
print(rank1_tensor.shape)

(2, 2)


In [ ]:
# Changing Shape of Tensors
# Number of elements of a tensor is the product of sizes of all it's shapes. There are often many shapes that have the 
# same number of elements, making it convenient to change the shape of the tensor.

tensor1 = tf.ones([1,2,3]) #tf.ones will create a tensor with ones, of shape [1,2,3]
tensor2 = tf.reshape(tensor1, [2,3,1]) #Reshapes existing data to [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]
                                                                             
# The numer of elements in the reshaped tensor MUST match the number in the original

In [ ]:
print(tensor1) #one tensor with 2 tensors with 3 dimensionality
print(tensor2) #2 tensorss with 3 tensors each with dimensionality of one
print(tensor3) # [3, -1] -> 3 tensors, previous val 3 so, 3-1, now 3 tensors with 2 tensors each, with dimensionality
# of the previous one, hence new shape is (3,2) 

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
test_tensor = tf.zeros([4,2,3]) # 4 tensors with 2 tensors each with dimensionailty of 3
print(test_tensor)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(4, 2, 3), dtype=float32)


In [ ]:
test_tensor2 = tf.reshape(test_tensor, [4, 6, 1]) #Number of values will be kept same when reshaping
print(test_tensor2)
print(test_tensor2.shape, test_tensor.shape)

tf.Tensor(
[[[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]], shape=(4, 6, 1), dtype=float32)
(4, 6, 1) (4, 2, 3)


In [ ]:
# When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. 
# Each subsequent value refrences a different dimension of the tensor.
matrix = [  [1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20]
                              ]
tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [ ]:

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
